import { ToolItem } from "@/types";

export const tools: ToolItem[] = [
  {
    name: "Calculadora de Salario Neto USA",
    slug: "calculadora-salario-neto-usa",
    description:
      "Compara dos ofertas y estima cuanto te quedaria despues de impuestos y deducciones con una simulacion orientativa de payroll en Estados Unidos.",
    category: "Finanzas",
    href: "/tools/calculadora-salario-neto-usa",
    detailHref: "/tools/calculadora-salario-neto-usa",
    launchHref: "/tools#calculadora-salario-neto-usa",
    isFeatured: true,
    updatedAt: "2026-03-14",
    intentLabel: "Decision financiera",
    decisionStage: "Estimar antes de aceptar o negociar",
    primaryOutcome: "Comparar dos ofertas con neto mensual y anual orientativo",
    bestFor: ["Ofertas laborales", "Presupuesto", "Comparar salarios"],
    keyBenefits: [
      "Ayuda a bajar dos ofertas de trabajo a una cifra mucho mas util para la vida real.",
      "Permite comparar escenarios por estado, periodicidad, bonus y ajustes payroll mas cercanos al neto real.",
      "Sirve como punto de partida antes de revisar payroll real o asesoramiento fiscal.",
    ],
    quickSteps: [
      "Carga dos ofertas lado a lado con salario, bonus y periodicidad.",
      "Ajusta estado, filing status, 401(k), deducciones y retencion extra.",
      "Usa el neto estimado para decidir con mas criterio.",
    ],
    trustPoints: [
      "La salida es una estimacion educativa, no un calculo fiscal oficial ni payroll definitivo.",
      "Social Security y Medicare siguen reglas mas estables; la parte federal, estatal y local sigue una aproximacion razonable pero no sustituye payroll real.",
      "Conviene contrastar el resultado con tu paystub real o con herramientas oficiales si vas a tomar una decision importante.",
    ],
    useCases: [
      "Comparar dos ofertas de trabajo antes de responder.",
      "Estimar cuanto dinero real llegaria al mes despues de descuentos.",
      "Entender mejor por que un paycheck puede verse mas bajo que el salario bruto.",
    ],
    relatedPostSlugs: ["calcular-salario-neto-estados-unidos-2026", "impuestos-freelancer-estados-unidos-2026"],
  },
  {
    name: "Generador de Resumenes",
    slug: "generador-de-resumenes",
    description:
      "Convierte textos largos en ideas clave para estudiar mas rapido.",
    category: "Estudio",
    href: "/tools/generador-de-resumenes",
    detailHref: "/tools/generador-de-resumenes",
    launchHref: "/tools#generador-de-resumenes",
    isFeatured: true,
    updatedAt: "2026-03-14",
    intentLabel: "Aplicacion inmediata",
    decisionStage: "Descubrir y sintetizar",
    primaryOutcome: "Extraer ideas clave rapido",
    bestFor: ["Estudiantes", "Lectura rapida", "Preparar repasos"],
    keyBenefits: [
      "Reduce textos largos a ideas centrales en menos tiempo.",
      "Facilita repasar antes de una entrega o examen.",
      "Ayuda a detectar estructura y argumentos principales.",
    ],
    quickSteps: [
      "Pega el texto o define el contenido a resumir.",
      "Identifica los puntos clave y ordenalos por prioridad.",
      "Convierte el resultado en un repaso corto o lista de accion.",
    ],
    trustPoints: [
      "Pensada para acelerar lectura, no para sustituir comprension.",
      "Conviene revisar el resumen final antes de entregar trabajo academico.",
      "Se recomienda combinarla con una lectura breve de verificacion.",
    ],
    useCases: [
      "Preparar apuntes antes de un examen.",
      "Reducir articulos largos a ideas esenciales.",
      "Sacar puntos accionables de documentos o briefings.",
    ],
    relatedPostSlugs: ["5-tecnicas-resumir-mejor", "organizar-semana-estudio-30-minutos"],
  },
  {
    name: "Organizador de Tareas",
    slug: "organizador-de-tareas",
    description: "Planifica entregas y prioridades semanales en minutos.",
    category: "Productividad",
    href: "/tools/organizador-de-tareas",
    detailHref: "/tools/organizador-de-tareas",
    launchHref: "/tools#organizador-de-tareas",
    isFeatured: true,
    updatedAt: "2026-03-14",
    intentLabel: "Organizacion operativa",
    decisionStage: "Priorizar y ejecutar",
    primaryOutcome: "Ordenar trabajo sin ruido",
    bestFor: ["Freelance", "Estudio", "Trabajo operativo"],
    keyBenefits: [
      "Ayuda a ordenar prioridades sin llenar la pantalla de ruido.",
      "Permite distinguir tareas urgentes, importantes y delegables.",
      "Reduce la friccion entre planificar y empezar a ejecutar.",
    ],
    quickSteps: [
      "Define entregas y tareas activas de la semana.",
      "Ordena por impacto y urgencia real.",
      "Ejecuta primero el bloque mas importante y revisa al final del dia.",
    ],
    trustPoints: [
      "Funciona mejor con pocas prioridades claras, no con listas infinitas.",
      "Util para estudio, trabajo remoto y rutinas operativas repetibles.",
      "No sustituye criterio: organiza la carga, no decide por ti.",
    ],
    useCases: [
      "Ordenar tareas academicas por fecha limite.",
      "Planificar semana de un proyecto freelance.",
      "Separar tareas profundas de recados operativos.",
    ],
    relatedPostSlugs: ["organizar-semana-estudio-30-minutos", "guia-ia-para-tareas"],
  },
  {
    name: "Corrector de Redaccion",
    slug: "corrector-de-redaccion",
    description:
      "Mejora ortografia y claridad antes de entregar trabajos.",
    category: "Escritura",
    href: "/tools/corrector-de-redaccion",
    detailHref: "/tools/corrector-de-redaccion",
    launchHref: "/tools#corrector-de-redaccion",
    isFeatured: true,
    updatedAt: "2026-03-14",
    intentLabel: "Revision final",
    decisionStage: "Pulir antes de entregar",
    primaryOutcome: "Mejorar claridad y correccion",
    bestFor: ["Entregas", "Correccion final", "Textos con IA"],
    keyBenefits: [
      "Mejora legibilidad antes de publicar, enviar o entregar.",
      "Ayuda a detectar frases ambiguas o poco naturales.",
      "Sirve como capa final para reducir errores evitables.",
    ],
    quickSteps: [
      "Pega el texto final o casi final.",
      "Revisa claridad, ortografia y repeticiones.",
      "Haz un ultimo repaso humano antes de compartirlo.",
    ],
    trustPoints: [
      "Conviene usarlo como revision final, no como sustituto de criterio editorial.",
      "Especialmente util en textos generados o apoyados por IA.",
      "La version final debe sonar natural y propia.",
    ],
    useCases: [
      "Revisar una tarea antes de entregarla.",
      "Pulir correos o propuestas cortas.",
      "Limpiar textos apoyados por inteligencia artificial.",
    ],
    relatedPostSlugs: ["guia-ia-para-tareas", "5-tecnicas-resumir-mejor"],
  },
  {
    name: "Temporizador Pomodoro",
    slug: "temporizador-pomodoro",
    description: "Gestiona sesiones de enfoque y descansos automaticamente.",
    category: "Productividad",
    href: "/tools/temporizador-pomodoro",
    detailHref: "/tools/temporizador-pomodoro",
    launchHref: "/tools#temporizador-pomodoro",
    isFeatured: true,
    updatedAt: "2026-03-14",
    intentLabel: "Foco inmediato",
    decisionStage: "Entrar en sesion de trabajo",
    primaryOutcome: "Sostener atencion por bloques",
    bestFor: ["Foco", "Bloques cortos", "Rutina diaria"],
    keyBenefits: [
      "Ayuda a iniciar trabajo profundo sin sobrepensar la duracion.",
      "Reduce dispersión en tareas largas o pesadas.",
      "Hace mas visible cuando toca parar y recuperar energia.",
    ],
    quickSteps: [
      "Elige una tarea concreta para el siguiente bloque.",
      "Trabaja en una sola cosa hasta que termine el ciclo.",
      "Descansa y reevalua antes del siguiente bloque.",
    ],
    trustPoints: [
      "Rinde mejor cuando la tarea ya esta definida de antemano.",
      "No sirve si la lista de trabajo sigue confusa o cambiante.",
      "Conviene combinarlo con un organizador de tareas sencillo.",
    ],
    useCases: [
      "Arrancar una sesion de estudio sin distracciones.",
      "Dividir trabajo mental pesado en bloques soportables.",
      "Controlar descansos en jornadas largas.",
    ],
    relatedPostSlugs: ["organizar-semana-estudio-30-minutos", "guia-ia-para-tareas"],
  },
];
